import Head from "next/head";
import Card from "../components/Card";
import H1 from "../components/type/H1";
import { getAbout } from "../lib/api";
import markdownToHtml from "../lib/markdownToHtml";

const About = ({ content }) => {
  return (
    <>
      <Head>
        <title>About | Marlies Gish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <H1>About</H1>
        <div dangerouslySetInnerHTML={{ __html: content }} />
      </Card>
    </>
  );
};

export default About;

export async function getStaticProps({ params }) {
  const aboutData = getAbout();
  const content = await markdownToHtml(aboutData);

  return {
    props: {
      content,
    },
  };
}
