import Head from "next/head";
import Card from "../components/Card";
import Main from "../components/layout/Main";
import H1 from "../components/type/H1";
import CONSTANTS from "../constants/constants";
import { getAbout } from "../lib/api";
import markdownToHtml from "../lib/markdownToHtml";

const About = ({ content }) => {
  return (
    <>
      <Head>
        <title>About | {CONSTANTS.pageTitleSuffix}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Card>
          <H1 bottomPadding>About</H1>
          <div dangerouslySetInnerHTML={{ __html: content }} />
        </Card>
      </Main>
    </>
  );
};

export default About;

export async function getStaticProps({ params }) {
  const aboutData = getAbout();
  const content = await markdownToHtml(aboutData);

  return {
    props: {
      content,
    },
  };
}
