import Head from "next/head";
import Card from "../components/Card";
import Masthead from "../components/Masthead";
import PostPreview from "../components/PostPreview";
import { getAllPosts } from "../lib/api";

export default function Blog({ allPosts }) {
  return (
    <>
      <Head>
        <title>Blog | Marlies Gish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <Masthead headline="Blog" />
        <div>
          {allPosts.map((post) => {
            return (
              <PostPreview
                key={post.slug}
                slug={post.slug}
                title={post.title}
                date={post.date}
                excerpt={post.excerpt}
              />
            );
          })}
        </div>
      </Card>
    </>
  );
}

export async function getStaticProps() {
  const allPosts = getAllPosts([
    "title",
    "date",
    "slug",
    "coverImage",
    "excerpt",
  ]);

  return {
    props: { allPosts },
  };
}
