import Head from "next/head";
import Card from "../components/Card";
import ConstraintWidth from "../components/layout/ConstraintWidth";
import Masthead from "../components/Masthead";
import PrimaryButton from "../components/buttons/PrimaryButton";
import PostPreview from "../components/PostPreview";
import SidePadding from "../components/SidePadding";
import H2 from "../components/type/H2";
import Paragraph from "../components/type/Paragraph";
import theme from "./../styles/theme";

export default function Home() {
  const posts = [];
  return (
    <div className="container">
      <Head>
        <title>Home | Marlies Gish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <SidePadding>
          <ConstraintWidth maxWidth={820}>
            <ConstraintWidth maxWidth={560} center>
              <Masthead
                center
                headline="A psychologist diving into the world of data science and Python"
              />
            </ConstraintWidth>
            <Paragraph>
              Welcome to my journey in becoming an experienced Data Scientist. In 2018 I completed my research
              Master in Psychology where I discovered the fun in exploring, analyzing and predicting data.
              The journey really started mid 2019 when my curiosity led me to
              learning Python, SQL and Power BI.
            </Paragraph>
          </ConstraintWidth>
        </SidePadding>
      </div>

      <Card>
        <H2>Recent posts</H2>
        {posts.map(({ node }, index) => {
          const title = node.frontmatter.title || node.fields.slug;
          return (
            <PostPreview
              key={node.fields.slug}
              slug={node.fields.slug}
              title={title}
              excerpt={node.excerpt}
              date={node.frontmatter.date}
            />
          );
        })}
        <div style={{ marginTop: 40 }}>
          <PrimaryButton href="/">See all posts</PrimaryButton>
        </div>
      </Card>
      <Card>
        <H2>About me</H2>
        <Paragraph>
          Let me answer this question by first introducing myself. I am a 30
          something year old, trying to follow my dreams and live my life as
          best as possible. Looking at my resume, you can see that I have always
          chosen to do and study what I think was interesting at that period of
          my life, without really looking what the future would bring choosing
          that path.{" "}
        </Paragraph>
        <PrimaryButton href="/">Read more</PrimaryButton>
      </Card>
      <style jsx>{`
        .main {
          background-color: ${theme.colors.primary};
          color: #fff;
          padding-bottom: 100px;
        }
        .cardOffset {
          margin-top: 0px;
        }

        .postTitle {
          color: rgba(0, 0, 0, 0.8);
          font-weight: 500;
        }

        .date {
          color: rgba(0, 0, 0, 0.6);
          line-height: 1;
        }
      `}</style>
    </div>
  );
}
