import Head from "next/head";
import ConstraintWidth from "../components/layout/ConstraintWidth";
import Masthead from "../components/Masthead";
import PrimaryButton from "../components/buttons/PrimaryButton";
import PostPreview from "../components/PostPreview";
import SidePadding from "../components/SidePadding";
import Paragraph from "../components/type/Paragraph";
import theme from "../styles/theme";
import { getAllPosts } from "../lib/api";
import Widget from "../components/Widget";
import Main from "../components/layout/Main";

const Index = ({ posts = [] }) => {
  return (
    <div className="container">
      <Head>
        <title>Home | Marlies Gish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="heading">
        <SidePadding>
          <ConstraintWidth maxWidth={820}>
            <ConstraintWidth maxWidth={560}>
              <Masthead
                center
                headline="A psychologist diving into the world of data science and Python"
              />
            </ConstraintWidth>
            <Paragraph>
              Welcome to my journey towards becoming an experienced Data
              Scientist. In 2018 I completed my Research Master in Psychology
              where I discovered the joy of exploring, analyzing and predicting
              data. The journey really started mid 2019 when my curiosity led me
              tolearning Python, SQL and Power BI.
            </Paragraph>
          </ConstraintWidth>
        </SidePadding>
      </div>

      <Main>
        <div className="grid">
          <Widget
            title="✍️ Latest blog post"
            buttons={
              <PrimaryButton block href="/blog">
                See all posts
              </PrimaryButton>
            }
          >
            {posts.map((post) => {
              return (
                <PostPreview
                  key={post.slug}
                  slug={post.slug}
                  title={post.title}
                  excerpt={post.excerpt}
                  date={post.date}
                />
              );
            })}
          </Widget>
          <Widget
            title="👩‍💻 About me"
            buttons={
              <PrimaryButton block href="/about">
                Read more
              </PrimaryButton>
            }
          >
            <Paragraph>
              Let me answer this question by first introducing myself. I am a 30
              something year old, trying to follow my dreams and live my life as
              best as possible.
            </Paragraph>
          </Widget>
          <Widget
            title="🤓 Things I'd like to learn"
            buttons={
              <PrimaryButton block href="/about">
                Read more
              </PrimaryButton>
            }
          >
            <Paragraph>
              Let me answer this question by first introducing myself. I am a 30
              something year old, trying to follow my dreams and live my life as
              best as possible. Looking at my resume, you can see that I have
              always chosen to do and study what I think was interesting at that
              period of my life, without really looking what the future would
              bring choosing that path.{" "}
            </Paragraph>
          </Widget>
          <Widget
            title="🤝 Get in touch"
            buttons={
              <>
                <PrimaryButton block href="mailto:me@marliesgish.com">
                  Email
                </PrimaryButton>
                <PrimaryButton block href="https://twitter.com/marliesgish">
                  Twitter
                </PrimaryButton>
              </>
            }
          >
            <Paragraph>
              Let me answer this question by first introducing myself. I am a 30
              something year old, trying to follow my dreams and live my life as
              best as possible. Looking at my resume, you can see that I have
              always chosen to do and study what I think was interesting at that
              period of my life, without really looking what the future would
              bring choosing that path.{" "}
            </Paragraph>
          </Widget>
        </div>
      </Main>
      <style jsx>{`
        .grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          column-gap: 20px;
          row-gap: 20px;
        }

        .heading {
          background-color: ${theme.colors.primary};
          color: #fff;
          padding-bottom: 100px;
        }
      `}</style>
    </div>
  );
};

export async function getStaticProps() {
  const allPosts = getAllPosts([
    "title",
    "date",
    "slug",
    "coverImage",
    "excerpt",
  ]);

  return {
    props: { posts: allPosts.slice(0, 1) }, // only show first 3 posts on homepage
  };
}

export default Index;
