import Head from "next/head";
import Card from "../components/Card";
import ConstraintWidth from "../components/layout/ConstraintWidth";
import Masthead from "../components/Masthead";
import PrimaryButton from "../components/buttons/PrimaryButton";
import PostPreview from "../components/PostPreview";
import SidePadding from "../components/SidePadding";
import H2 from "../components/type/H2";
import Paragraph from "../components/type/Paragraph";
import theme from "../styles/theme";
import { getAllPosts } from "../lib/api";

const Index = ({ posts = [] }) => {
  return (
    <div className="container">
      <Head>
        <title>Home | Marlies Gish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <SidePadding>
          <ConstraintWidth maxWidth={820}>
            <ConstraintWidth maxWidth={560}>
              <Masthead
                center
                headline="A psychologist diving into the world of data science and Python"
              />
            </ConstraintWidth>
            <Paragraph>
              Welcome to my journey in becoming an experienced Data Scientist.
              In 2018 I completed my research Master in Psychology where I
              discovered the fun in exploring, analyzing and predicting data.
              The journey really started mid 2019 when my curiosity led me to
              learning Python, SQL and Power BI.
            </Paragraph>
          </ConstraintWidth>
        </SidePadding>
      </div>

      <Card>
        <H2>Recent blog posts</H2>
        {posts.map((post) => {
          return (
            <PostPreview
              key={post.slug}
              slug={post.slug}
              title={post.title}
              excerpt={post.excerpt}
              date={post.date}
            />
          );
        })}
        <div style={{ marginTop: 40 }}>
          <PrimaryButton href="/blog">See all posts</PrimaryButton>
        </div>
      </Card>
      <Card>
        <H2>About me</H2>
        <Paragraph>
          Let me answer this question by first introducing myself. I am a 30
          something year old, trying to follow my dreams and live my life as
          best as possible. Looking at my resume, you can see that I have always
          chosen to do and study what I think was interesting at that period of
          my life, without really looking what the future would bring choosing
          that path.{" "}
        </Paragraph>
        <PrimaryButton href="/about">Read more</PrimaryButton>
      </Card>
      <style jsx>{`
        .main {
          background-color: ${theme.colors.primary};
          color: #fff;
          padding-bottom: 100px;
        }
        .cardOffset {
          margin-top: 0px;
        }

        .postTitle {
          color: rgba(0, 0, 0, 0.8);
          font-weight: 500;
        }

        .date {
          color: rgba(0, 0, 0, 0.6);
          line-height: 1;
        }
      `}</style>
    </div>
  );
};

export async function getStaticProps() {
  const allPosts = getAllPosts([
    "title",
    "date",
    "slug",
    "coverImage",
    "excerpt",
  ]);

  return {
    props: { posts: allPosts.slice(0, 3) }, // only show first 3 posts on homepage
  };
}

export default Index;
