import Head from "next/head";
import Card from "../components/Card";
import ResumeItem from "../components/ResumeItem";
import H1 from "../components/type/H1";
import H2 from "../components/type/H2";
import Paragraph from "../components/type/Paragraph";

const Resume = ({ allPosts }) => {
  return (
    <>
      <Head>
        <title>Resume | Marlies Gish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <H1>Resume</H1>

        <H2>Profile</H2>
        <Paragraph>
          In the world of data, new developments are constantly occurring. It is
          this aspect, combined with the love for new challenges, that attracted
          me to the world of Big Data and Data Science. In addition, working
          with data offers me many opportunities to combine two of my best
          skills: analytical thinking and excellent communication skills. My
          affinity for data is strongly linked to the insight that all data has
          the potential to be valuable. Everywhere there are hidden treasures of
          data, which can be transformed into useful information and of which
          insightful predictions can be made.
        </Paragraph>
        <hr className="hr" />
        <H2>Work experience</H2>
        <ResumeItem
          position="Data Specialist"
          company="Novalinq"
          location="Haarlem"
          website="https://www.novalinq.nl"
          date="Apr '21 - Present"
          content="The main tasks are converting Big Data into Datawarehouses after which analyses can be done to improve business processes, using Azure, Data Factory, Databricks, Spark, SQL, Python and Power BI. In addition, part of my job responsibilities include teaching the basics of Data Engineering and Data Analysis to students."
        />
        <ResumeItem
          position="Data Analyst and Psychologist"
          company="Trubendorffer"
          location="Amsterdam"
          website="https://www.trubendorffer.nl"
          date="Mar '17 - Present"
          content="At Trubendorffer I started my work as a psychologist. Soon I realized that I had more affinity with analytical thinking and I got the opportunity to start small projects related to Data Analysis. One of the main projects was to link the Diagnosis Treatment Combination (DBC) with the new Healthcare Performance Model (ZPM), after which predictions could be made about future finances. I mainly used SQL queries for this project."
        />
        <ResumeItem
          position="Research Assistent"
          company="Rivierduinen"
          location="Leiden"
          website="https://www.rivierduinen.nl"
          date="Aug '18 - Mar '19"
          content="Within this position, I supported PHD students with their researches. Among other things, I helped them to write research proposals and to start the research in practice."
        />
        <ResumeItem
          position="Student Assistent"
          company="Leiden University"
          location="Leiden"
          website="https://www.universiteitleiden.nl/en"
          date="Apr 18 - Jul '18"
          content="As a Student Assistant, I helped professors with the teaching materials. I also supported in reviewing essays."
        />
        <hr className="hr" />
        <H2>Internships</H2>
        <ResumeItem
          position="Research Assistent"
          company="Leiden University"
          location="Leiden"
          website="https://www.universiteitleiden.nl/en"
          date="Aug '16 - Mar '17"
          content="During this internship I did research in the Effets of Oxytocine on brain activity. I also wrote my master thesis about this topic."
        />
        <ResumeItem
          position="Research Assistent"
          company="Brijder"
          location="The Hague"
          website="https://www.brijder.nl"
          date="Jul '16 - Jan '17"
          content="With the internship at Brijder, I assisted in research on Post Traumatic Stress Disorder (PSTD) in patients with a severe substance abuse disorder."
        />
        <hr className="hr" />
        <H2>Education</H2>
        <ResumeItem
          position="Business and Data Analytics"
          company="HvA"
          location="Amsterdam"
          website="https://www.amsterdamuas.com"
          date="Sep '20 - Feb '21"
          content="This course was primarily focused on Business Intelligence and Data Processing. Topics included Business Processes, Data Warehousing, and Data Visualization, using Visual Studio, SQL, Python and Power BI."
        />
        <ResumeItem
          position="Research Master Psychology"
          company="Leiden University"
          location="Leiden"
          website="https://www.universiteitleiden.nl/en"
          date="Sep '15 - Apr '18"
          content="This Master's Program was all about statistics and research in Mental Health. Critically analyzing published articles while learning comprehensive statistical tests were an important part of the study. During this study I made use of R and SPSS for the statistical part."
        />
        <ResumeItem
          position="Health Sciences"
          company="Maastricht University"
          location="Maastricht"
          website="https://www.maastrichtuniversity.nl"
          date="Sep '12 - Jul '15"
          content="The Major consisted of topics focused on Mental Health. As a Minor, I chose a Ethics and Social Philosophy at the Vrije Universiteit van Amsterdam (VU)."
        />
        <ResumeItem
          position="Psychosocial Counseling"
          company="Psychodidact"
          location="Den Bosch"
          website="https://www.psychodidact.nl"
          date="Jan '10 - Feb '14"
          content="Psychosocial Counseling was a four year Higher Professional Education where the basics of psychology and communication skills were discussed and practiced."
        />
        <ResumeItem
          position="Nature and Health"
          company="Sint Antoniuscollege"
          location="Gouda"
          website=""
          date="Sep '01 - Jul '07"
          content="At High School I completed my Pre University Education and chose the profile Nature and Health."
        />
        <style jsx>{`
          .hr {
            border: 0;
            border-top: 1px solid rgba(0, 0, 0, 0.1);
            margin-top: 50px;
            margin-bottom: 50px;
          }
        `}</style>
      </Card>
    </>
  );
};

export default Resume;
